spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    jwtExpirationInMs: ${JWT_EXPIRATION} # 1-hour

  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api/v1
  port: 3000
